### ISSUE TITLE
Jest - ReferenceError: SVGAnimatedString is not defined

### ISSUE THREAD

**Issue by ahulab** [Akryum/v-tooltip#76]
## Description

We are using v-tooltip in our project and noticed that Jest will throw errors when tooltip is imported into a component directly and used as a directive. **NOTE** the errors do not occur when the plugin is installed into vue globally. 

## Problem 
After running jest: 

```
console.error node_modules/vue/dist/vue.runtime.common.js:1685
      ReferenceError: SVGAnimatedString is not defined
          at addClasses (/Users/home/Projects/vueApp/node_modules/v-tooltip/dist/v-tooltip.umd.js:2456:30)
          at createTooltip (/Users/home/Projects/vueApp/node_modules/v-tooltip/dist/v-tooltip.umd.js:3450:2)
          at bind (/Users/home/Projects/vueApp/node_modules/v-tooltip/dist/v-tooltip.umd.js:3482:3)
          at callHook$1 (/Users/home/Projects/vueApp/node_modules/vue/dist/vue.runtime.common.js:6073:7)
          at _update (/Users/home/Projects/vueApp/node_modules/vue/dist/vue.runtime.common.js:5998:7)
          at Array.updateDirectives (/Users/home/Projects/vueApp/node_modules/vue/dist/vue.runtime.common.js:5979:5)
          at invokeCreateHooks (/Users/home/Projects/vueApp/node_modules/vue/dist/vue.runtime.common.js:5510:22)
          at createElm (/Users/home/Projects/vueApp/node_modules/vue/dist/vue.runtime.common.js:5401:11)
          at createChildren (/Users/home/Projects/vueApp/node_modules/vue/dist/vue.runtime.common.js:5494:9)
          at createElm (/Users/home/Projects/vueApp/node_modules/vue/dist/vue.runtime.common.js:5399:9)
          at VueComponent.patch [as __patch__] (/Users/home/Projects/vueApp/node_modules/vue/dist/vue.runtime.common.js:5877:7)
          at VueComponent.Vue._update (/Users/home/Projects/vueApp/node_modules/vue/dist/vue.runtime.common.js:2560:19)
          at VueComponent.updateComponent (/Users/home/Projects/vueApp/node_modules/vue/dist/vue.runtime.common.js:2688:10)
          at Watcher.get (/Users/home/Projects/vueApp/node_modules/vue/dist/vue.runtime.common.js:3031:25)
          at new Watcher (/Users/home/Projects/vueApp/node_modules/vue/dist/vue.runtime.common.js:3020:12)
          at mountComponent (/Users/home/Projects/vueApp/node_modules/vue/dist/vue.runtime.common.js:2692:17)
          at VueComponent.Object.<anonymous>.Vue$3.$mount (/Users/home/Projects/vueApp/node_modules/vue/dist/vue.runtime.common.js:7731:10)
          at mount (/Users/home/Projects/vueApp/node_modules/vue-test-utils/dist/vue-test-utils.js:1277:8)
          at shallow (/Users/home/Projects/vueApp/node_modules/vue-test-utils/dist/vue-test-utils.js:1297:10)
          at Object.<anonymous> (/Users/home/Projects/vueApp/test/unit/specs/modules/DNS/DNSView.spec.js:7:41)
          at Object.asyncFn (/Users/home/Projects/vueApp/node_modules/jest-jasmine2/build/jasmine_async.js:122:61)
          at e (/Users/home/Projects/vueApp/node_modules/jest-jasmine2/build/queue_runner.js:46:12)
          at mapper (/Users/home/Projects/vueApp/node_modules/jest-jasmine2/build/queue_runner.js:34:499)
          at promise.then (/Users/home/Projects/vueApp/node_modules/jest-jasmine2/build/queue_runner.js:74:39)
          at process._tickCallback (internal/process/next_tick.js:103:7)
```

## Local solution
I got rid of this error locally by adding the following lines to our jest config. But I don't believe that's the correct way for this to be handled
```
global.SVGAnimatedString = () => {};
global.SVGElement = () => {};
```

**Comment by Akryum** [comment]
JSDom doesn't support SVG yet. [Here](https://github.com/Akryum/v-tooltip/blob/master/tests/unit/jest-setup.js) is what I did.

**Comment by ahulab** [comment]
@Akryum thank you
