### ISSUE TITLE
v-tooltip@vue3 ie "^4.0.0-alpha.1" is not compatible with Server Side Rendering

### ISSUE THREAD

**Issue by runxc1** [Akryum/v-tooltip#797]
I have a rather new project that I have been using v-tooltip in that is a vue3 project.  It builds and runs in the browser but I have had build errors and unable to get a SSR build working.  After slowly removing every piece of the application I have found that it builds when I remove v-tooltip from the project.   The error log from the error is given below.

```12 info lifecycle fullcal@0.1.0~build:server: Failed to exec build:server script
13 verbose stack Error: fullcal@0.1.0 build:server: `cross-env SSR=1 vue-cli-service build --dest ./server`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\bferr\AppData\Roaming\nvm\v10.14.1\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\bferr\AppData\Roaming\nvm\v10.14.1\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid fullcal@0.1.0
15 verbose cwd C:\dev\CitySpark\CitySpark.Portal\JsBuild\fullcal
```
I tried multiple nodejs versions and installed the node modules over and over and finally got it building when I removed v-tooltip.

**Comment by Akryum** [comment]
Should work on latest v4 beta
